name       : fontconfig
version    : 2.13.0
release    : 32
source     :
    - https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.0.tar.bz2 : 91dde8492155b7f34bb95079e79be92f1df353fcc682c19be90762fd3e12eeb9
license    :
    - MIT
    - HPND
summary    : Font configuration utilities
component  : desktop.library
description: |
    The Fontconfig package contains a library and support programs used for configuring and customizing font access
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(expat)
    - pkgconfig32(uuid)
    - gperf
rundeps    :
    - harfbuzz
    - 32bit : harfbuzz-32bit
patterns   :
    - devel :
        - /usr/share/man/man3
    - docs :
        - /usr/share/doc/fontconfig/fontconfig-devel
emul32     : yes
setup      : |
    %apply_patches
    %reconfigure --disable-static \
                 --with-default-hinting=slight \
                 --with-baseconfigdir=/usr/share/fonts \
                 --with-configdir=/usr/share/fonts/conf.d
build      : |
    %make
install    : |
    %make_install
    if [[ -z "${EMUL32BUILD}" ]]; then
        install -dm00644 $installdir/etc
        ln -s /usr/share/fonts $installdir/etc/fonts
    fi

    install -D -m 00755 $pkgfiles/fontconfig.tmpfiles $installdir/%libdir%/tmpfiles.d/fontconfig.conf
    rm -rf $installdir/var
