name       : fontconfig
version    : 2.12.1
release    : 26
source     :
    - https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.12.1.tar.gz : a9f42d03949f948a3a4f762287dbc16e53a927c91a07ee64207ebd90a9e5e292
license    :
    - MIT
    - HPND
summary    : Font configuration utilities
component  : desktop.library
description: |
    The Fontconfig package contains a library and support programs used for configuring and customizing font access
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(expat)
    - gperf
patterns   :
    - devel :
        - /usr/share/man/man3
    - docs :
        - /usr/share/doc/fontconfig/fontconfig-devel
emul32     : yes
setup      : |
    %apply_patches
    %reconfigure --prefix=/usr \
                 --disable-static \
                 --with-default-hinting=slight \
                 --with-baseconfigdir=/usr/share/fonts \
                 --with-configdir=/usr/share/fonts/conf.d
build      : |
    %make
install    : |
    %make_install
    install -D -m 00755 $pkgfiles/fontconfig.tmpfiles $installdir/%libdir%/tmpfiles.d/fontconfig.conf
    rm -rf $installdir/var
